<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Paygate.Audit\Paygate.Audit.csproj" />
    <ProjectReference Include="..\Paygate.Notification\Paygate.Notification.csproj" />
    <ProjectReference Include="..\Paygate.Consumers.Common\Paygate.Consumers.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="4.0.0.16" />
    <PackageReference Include="Amazon.Lambda.Core" Version="2.5.0" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="3.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
